# Generated by Django 3.1.2 on 2020-10-12 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('name', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'school',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(db_column='userID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('phone_number', models.CharField(blank=True, max_length=45, null=True)),
                ('profile_photo', models.CharField(max_length=45)),
                ('gender', models.CharField(max_length=45)),
                ('role', models.CharField(max_length=45)),
                ('department_name', models.ForeignKey(db_column='department_name', on_delete=django.db.models.deletion.CASCADE, to='alldata.department')),
                ('school_name', models.ForeignKey(db_column='school_name', on_delete=django.db.models.deletion.CASCADE, to='alldata.school')),
            ],
            options={
                'db_table': 'user',
                'unique_together': {('userid', 'first_name')},
            },
        ),
        migrations.AddField(
            model_name='department',
            name='school_name',
            field=models.ForeignKey(db_column='school_name', on_delete=django.db.models.deletion.CASCADE, to='alldata.school'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentid', models.AutoField(db_column='studentID', primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=45)),
                ('year_of_study', models.IntegerField()),
                ('academic_status', models.CharField(max_length=45)),
                ('schedule_approve', models.BooleanField(default=False)),
                ('schedule_lock', models.BooleanField(default=False)),
                ('user_userid', models.ForeignKey(db_column='user_userID', on_delete=django.db.models.deletion.CASCADE, to='alldata.user')),
            ],
            options={
                'db_table': 'student',
                'unique_together': {('studentid', 'user_userid')},
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructorid', models.AutoField(db_column='instructorID', primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=45)),
                ('user_userid', models.ForeignKey(db_column='user_userID', on_delete=django.db.models.deletion.CASCADE, to='alldata.user')),
            ],
            options={
                'db_table': 'instructor',
                'unique_together': {('instructorid', 'user_userid')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name',)},
        ),
    ]
