# Generated by Django 3.1.2 on 2020-10-12 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alldata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseid', models.AutoField(db_column='courseID', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45)),
                ('credits', models.IntegerField()),
                ('level', models.IntegerField()),
                ('description', models.CharField(max_length=45)),
                ('department_name', models.ForeignKey(db_column='department_name', on_delete=django.db.models.deletion.DO_NOTHING, to='alldata.department')),
            ],
            options={
                'db_table': 'course',
                'unique_together': {('courseid', 'title', 'department_name')},
            },
        ),
    ]
