# Generated by Django 3.1.2 on 2020-10-12 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alldata', '0003_auto_20201012_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=45)),
                ('is_optional', models.BooleanField(default=False)),
                ('course_courseid', models.ForeignKey(db_column='course_courseID', on_delete=django.db.models.deletion.CASCADE, to='alldata.course')),
                ('req_course_courseid', models.ForeignKey(db_column='req_course_courseID', on_delete=django.db.models.deletion.CASCADE, related_name='requisite_course', to='alldata.course')),
            ],
            options={
                'db_table': 'requisite',
                'unique_together': {('course_courseid', 'req_course_courseid', 'type')},
            },
        ),
    ]
