# Generated by Django 3.1.2 on 2020-10-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldata', '0004_requisite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrationdate',
            fields=[
                ('registrationid', models.AutoField(db_column='registrationID', primary_key=True, serialize=False)),
                ('priority', models.IntegerField()),
                ('year', models.IntegerField()),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'registrationDate',
            },
        ),
    ]
