# Generated by Django 3.1.2 on 2020-10-12 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alldata', '0005_registrationdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coursesection',
            fields=[
                ('sectionid', models.AutoField(db_column='sectionID', primary_key=True, serialize=False)),
                ('num_type', models.CharField(max_length=45)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('semester', models.CharField(max_length=45)),
                ('capacity', models.IntegerField()),
                ('room', models.CharField(max_length=45)),
                ('total_points', models.IntegerField()),
                ('course_courseid', models.ForeignKey(db_column='course_courseID', on_delete=django.db.models.deletion.CASCADE, to='alldata.course')),
            ],
            options={
                'db_table': 'courseSection',
                'unique_together': {('sectionid', 'course_courseid')},
            },
        ),
    ]
