# Generated by Django 3.1.2 on 2020-10-12 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alldata', '0006_coursesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sectionday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=45)),
                ('coursesection_sectionid', models.ForeignKey(db_column='courseSection_sectionID', on_delete=django.db.models.deletion.CASCADE, to='alldata.coursesection')),
            ],
            options={
                'db_table': 'sectionDay',
            },
        ),
    ]
