# Generated by Django 3.1.2 on 2020-10-12 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alldata', '0007_sectionday'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_courseid', models.ForeignKey(db_column='course_courseID', on_delete=django.db.models.deletion.CASCADE, to='alldata.course')),
                ('student_studentid', models.ForeignKey(db_column='student_studentID', on_delete=django.db.models.deletion.CASCADE, to='alldata.student')),
            ],
            options={
                'db_table': 'student_enrollment',
                'unique_together': {('student_studentid', 'course_courseid')},
            },
        ),
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_courseid', models.ForeignKey(db_column='course_courseID', on_delete=django.db.models.deletion.CASCADE, to='alldata.course')),
                ('instructor_instructorid', models.ForeignKey(db_column='instructor_instructorID', on_delete=django.db.models.deletion.CASCADE, to='alldata.instructor')),
            ],
            options={
                'db_table': 'course_instructor',
                'unique_together': {('instructor_instructorid', 'course_courseid')},
            },
        ),
        migrations.CreateModel(
            name='CourseGrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midterm_grade', models.CharField(blank=True, max_length=45, null=True)),
                ('final_grade', models.CharField(blank=True, max_length=45, null=True)),
                ('course_courseid', models.ForeignKey(db_column='course_courseID', on_delete=django.db.models.deletion.CASCADE, to='alldata.course')),
                ('student_studentid', models.ForeignKey(db_column='student_studentID', on_delete=django.db.models.deletion.CASCADE, to='alldata.student')),
            ],
            options={
                'db_table': 'course_grades',
                'unique_together': {('student_studentid', 'course_courseid')},
            },
        ),
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_instructorid', models.ForeignKey(db_column='instructor_instructorID', on_delete=django.db.models.deletion.CASCADE, to='alldata.instructor')),
                ('student_studentid', models.ForeignKey(db_column='student_studentID', on_delete=django.db.models.deletion.CASCADE, to='alldata.student')),
            ],
            options={
                'db_table': 'advice',
                'unique_together': {('instructor_instructorid', 'student_studentid')},
            },
        ),
    ]
