# Generated by Django 3.1.2 on 2020-10-12 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alldata', '0008_advice_coursegrades_courseinstructor_studentenrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coursepagemodule',
            fields=[
                ('moduleid', models.AutoField(db_column='moduleID', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45)),
                ('order', models.IntegerField()),
                ('coursesection_sectionid', models.ForeignKey(db_column='courseSection_sectionID', on_delete=django.db.models.deletion.CASCADE, to='alldata.coursesection')),
            ],
            options={
                'db_table': 'coursePageModule',
                'unique_together': {('moduleid', 'coursesection_sectionid')},
            },
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('discussionid', models.AutoField(db_column='discussionID', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45)),
                ('coursepagemodule_moduleid', models.ForeignKey(db_column='coursePageModule_moduleID', on_delete=django.db.models.deletion.CASCADE, to='alldata.coursepagemodule')),
            ],
            options={
                'db_table': 'discussion',
                'unique_together': {('discussionid', 'coursepagemodule_moduleid')},
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('fileid', models.AutoField(db_column='fileID', primary_key=True, serialize=False)),
                ('placeid', models.CharField(db_column='placeID', max_length=45)),
                ('type', models.CharField(max_length=45)),
                ('url', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'file',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quizid', models.AutoField(db_column='quizID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=45)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('time_limit', models.TimeField()),
                ('max_poit', models.IntegerField()),
                ('coursepagemodule_moduleid', models.ForeignKey(db_column='coursePageModule_moduleID', on_delete=django.db.models.deletion.CASCADE, to='alldata.coursepagemodule')),
            ],
            options={
                'db_table': 'quiz',
                'unique_together': {('quizid', 'coursepagemodule_moduleid')},
            },
        ),
        migrations.CreateModel(
            name='Quizquestion',
            fields=[
                ('questionid', models.AutoField(db_column='questionID', primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=45)),
                ('is_open', models.BooleanField(default=False)),
                ('points', models.IntegerField()),
                ('quiz_quizid', models.ForeignKey(db_column='quiz_quizID', on_delete=django.db.models.deletion.CASCADE, to='alldata.quiz')),
            ],
            options={
                'db_table': 'quizQuestion',
                'unique_together': {('questionid', 'quiz_quizid')},
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignmentid', models.AutoField(db_column='assignmentID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=45)),
                ('start_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('max_point', models.IntegerField()),
                ('coursepagemodule_moduleid', models.ForeignKey(db_column='coursePageModule_moduleID', on_delete=django.db.models.deletion.CASCADE, to='alldata.coursepagemodule')),
            ],
            options={
                'db_table': 'assignment',
                'unique_together': {('assignmentid', 'coursepagemodule_moduleid')},
            },
        ),
        migrations.CreateModel(
            name='Answerchoice',
            fields=[
                ('answerid', models.AutoField(db_column='answerID', primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=45)),
                ('is_right', models.BooleanField(default=False)),
                ('quizquestion_questionid', models.ForeignKey(db_column='quizQuestion_questionID', on_delete=django.db.models.deletion.CASCADE, to='alldata.quizquestion')),
            ],
            options={
                'db_table': 'answerChoice',
                'unique_together': {('answerid', 'quizquestion_questionid')},
            },
        ),
        migrations.CreateModel(
            name='AnnouncementNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_object_id', models.IntegerField()),
                ('time', models.TimeField()),
                ('is_turned_on', models.BooleanField(default=False)),
                ('user_userid', models.ForeignKey(db_column='user_userID', on_delete=django.db.models.deletion.CASCADE, to='alldata.user')),
            ],
            options={
                'db_table': 'announcement_notification',
            },
        ),
        migrations.CreateModel(
            name='Quizsubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerchoice_answerid', models.OneToOneField(db_column='answerChoice_answerID', on_delete=django.db.models.deletion.CASCADE, to='alldata.answerchoice')),
                ('quiz_quizid', models.ForeignKey(db_column='quiz_quizID', on_delete=django.db.models.deletion.CASCADE, to='alldata.quiz')),
                ('quizquestion_questionid', models.OneToOneField(db_column='quizQuestion_questionID', on_delete=django.db.models.deletion.CASCADE, to='alldata.quizquestion')),
                ('student_studentid', models.ForeignKey(db_column='student_studentID', on_delete=django.db.models.deletion.CASCADE, to='alldata.student')),
            ],
            options={
                'db_table': 'quizSubmission',
                'unique_together': {('student_studentid', 'quizquestion_questionid', 'quiz_quizid', 'answerchoice_answerid')},
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=45)),
                ('date', models.DateTimeField()),
                ('discussion_discussionid', models.ForeignKey(db_column='discussion_discussionID', on_delete=django.db.models.deletion.CASCADE, to='alldata.discussion')),
                ('user_userid', models.ForeignKey(db_column='user_userID', on_delete=django.db.models.deletion.CASCADE, to='alldata.user')),
            ],
            options={
                'db_table': 'post',
                'unique_together': {('user_userid', 'discussion_discussionid')},
            },
        ),
        migrations.CreateModel(
            name='Assignmentsubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, unique=True)),
                ('points', models.IntegerField()),
                ('feedback', models.CharField(blank=True, max_length=45, null=True)),
                ('assignment_assignmentid', models.ForeignKey(db_column='assignment_assignmentID', on_delete=django.db.models.deletion.CASCADE, to='alldata.assignment')),
                ('student_studentid', models.ForeignKey(db_column='student_studentID', on_delete=django.db.models.deletion.CASCADE, to='alldata.student')),
            ],
            options={
                'db_table': 'assignmentSubmission',
                'unique_together': {('assignment_assignmentid', 'student_studentid')},
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('announcementid', models.AutoField(db_column='announcementID', primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=45)),
                ('date', models.DateTimeField()),
                ('coursesection_sectionid', models.ForeignKey(db_column='courseSection_sectionID', on_delete=django.db.models.deletion.CASCADE, to='alldata.coursesection')),
            ],
            options={
                'db_table': 'announcement',
                'unique_together': {('announcementid', 'coursesection_sectionid')},
            },
        ),
    ]
