# Generated by Django 3.1.2 on 2020-10-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldata', '0009_announcement_announcementnotification_answerchoice_assignment_assignmentsubmission_coursepagemodule_'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
