# Generated by Django 3.1.2 on 2020-11-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldata', '0011_auto_20201020_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_of_study',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)]),
        ),
    ]
