# Generated by Django 3.1.2 on 2020-11-09 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alldata', '0012_auto_20201106_0539'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
