# Generated by Django 3.1.2 on 2020-11-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldata', '0014_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionday',
            name='day',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday')], max_length=45),
        ),
    ]
