# Generated by Django 2.2.12 on 2020-11-16 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alldata', '0014_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
