# Generated by Django 2.2.12 on 2020-11-16 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alldata', '0015_delete_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('fileid', models.AutoField(db_column='fileID', primary_key=True, serialize=False)),
                ('placeName', models.CharField(choices=[('assignment', 'assignment'), ('submission', 'submission'), ('course', 'course')], max_length=45)),
                ('url', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('coursepagemodule_moduleid', models.ForeignKey(db_column='coursePageModule_moduleID', on_delete=django.db.models.deletion.CASCADE, to='alldata.Coursepagemodule')),
            ],
            options={
                'db_table': 'file',
            },
        ),
    ]
