# Generated by Django 2.2.12 on 2020-11-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldata', '0016_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='close_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='open_time',
            field=models.DateTimeField(),
        ),
    ]
