# Generated by Django 2.2.12 on 2020-11-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldata', '0017_auto_20201116_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='myFile',
            field=models.FileField(default='default.jpg', upload_to=''),
        ),
    ]
