# Generated by Django 2.2.12 on 2020-11-16 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alldata', '0018_assignment_myfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='myFile',
        ),
    ]
