# Generated by Django 2.2.12 on 2020-11-16 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alldata', '0015_auto_20201115_1230'),
        ('alldata', '0020_auto_20201116_1556'),
    ]

    operations = [
    ]
