# Generated by Django 2.2.12 on 2020-11-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldata', '0021_merge_20201116_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='placeName',
        ),
        migrations.RemoveField(
            model_name='file',
            name='url',
        ),
        migrations.AddField(
            model_name='file',
            name='myFile',
            field=models.FileField(default='default.jpg', upload_to=''),
        ),
    ]
