# Generated by Django 3.0 on 2021-02-22 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alldata', '0023_auto_20210210_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='department_name',
            field=models.ForeignKey(db_column='department_name', default='Computer Science', on_delete=django.db.models.deletion.CASCADE, to='alldata.Department'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='priority',
            unique_together={('course_courseid', 'department_name', 'type')},
        ),
    ]
