# Generated by Django 3.1.6 on 2021-03-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldata', '0024_auto_20210222_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='is_ans',
            field=models.BooleanField(default=False),
        ),
    ]
