# Generated by Django 3.0 on 2021-03-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldata', '0026_quizquestion_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priority',
            name='id',
        ),
        migrations.AlterField(
            model_name='priority',
            name='year',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], primary_key=True, serialize=False),
        ),
    ]
