# Generated by Django 3.0 on 2021-03-09 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alldata', '0027_auto_20210308_1457'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Priority',
        ),
    ]
