# Generated by Django 3.0 on 2021-03-09 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alldata', '0029_delete_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)])),
                ('type', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
                ('course_courseid', models.ForeignKey(db_column='course_courseID', on_delete=django.db.models.deletion.CASCADE, to='alldata.Course')),
                ('department_name', models.ForeignKey(db_column='department_name', on_delete=django.db.models.deletion.CASCADE, to='alldata.Department')),
            ],
            options={
                'verbose_name': 'Priority for Course',
                'db_table': 'priority',
                'unique_together': {('course_courseid', 'department_name', 'year')},
            },
        ),
    ]
