# Generated by Django 3.0 on 2021-03-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldata', '0030_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='section_type',
            field=models.CharField(choices=[('Lecture', 'Lecture'), ('Seminar', 'Seminar'), ('Recitation', 'Recitation'), ('Lab', 'Lab')], default='Lecture', max_length=45),
        ),
    ]
