# Generated by Django 3.0 on 2021-03-10 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alldata', '0031_coursesection_section_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requisite',
            unique_together={('course_courseid', 'req_course_courseid')},
        ),
    ]
