# Generated by Django 3.1.6 on 2021-04-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldata', '0032_auto_20210310_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='textTwo',
            field=models.CharField(default='default value', max_length=250),
        ),
    ]
